// GENERATED BY scripts/generate-agent-packages.py; DO NOT EDIT.
// This content-only entry activates the manifest-declared skill roots without
// registering tools, services, hooks, providers, or configuration side effects.

export default {
  id: "agent-writing",
  name: "Agent Writing",
  description: "Investigate, draft, and edit with three writing voices working as a team of rivals.",
  register() {},
};
