// GENERATED BY scripts/generate-agent-packages.py; DO NOT EDIT.
// This content-only entry activates the manifest-declared skill roots without
// registering tools, services, hooks, providers, or configuration side effects.

export default {
  id: "agent-seo",
  name: "Agent SEO",
  description: "Research, write, fact-check, and optimize long-form SEO content.",
  register() {},
};
