// GENERATED BY scripts/generate-agent-packages.py; DO NOT EDIT.
// This content-only entry activates the manifest-declared skill roots without
// registering tools, services, hooks, providers, or configuration side effects.

export default {
  id: "llm-wiki",
  name: "LLM Wiki",
  description: "Create and query project wikis with optional maintenance automation.",
  register() {},
};
