import json
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from scripts.plugin_surfaces import (
    canonical_semantic_bytes,
    generate_files,
    generated_drift,
    generator_owned_paths,
    load_contract,
    validate_isolated_packages,
    validate_package_tree,
    write_generated_files,
)


REPO_ROOT = Path(__file__).resolve().parents[1]


class GeneratedPackageTests(unittest.TestCase):
    def test_checked_in_generation_matches_deterministic_render(self):
        first = generate_files(REPO_ROOT)
        second = generate_files(REPO_ROOT)
        self.assertEqual(first, second)
        mismatches = [path for path, content in first.items() if (REPO_ROOT / path).read_bytes() != content]
        self.assertEqual([], mismatches)
        self.assertEqual(set(first), generator_owned_paths(REPO_ROOT))

    def test_screenote_allowlist_is_generated_from_contract(self):
        relative = "plugins/screenote/scripts/screenote-approved-commands.sh"
        rendered = generate_files(REPO_ROOT)[relative].decode()
        self.assertIn("GENERATED BY scripts/generate-agent-packages.py", rendered)
        self.assertIn("SCREENOTE_APPROVED_COMMANDS", rendered)
        self.assertIn("screenote_command_is_approved", rendered)
        syntax = subprocess.run(
            ["bash", "-n", str(REPO_ROOT / relative)],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(0, syntax.returncode, syntax.stdout + syntax.stderr)
        behavior = subprocess.run(
            [
                "bash",
                "-c",
                'source "$1"; screenote_command_is_approved project list; ! screenote_command_is_approved project delete',
                "allowlist-test",
                str(REPO_ROOT / relative),
            ],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(0, behavior.returncode, behavior.stdout + behavior.stderr)

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            shutil.copytree(REPO_ROOT, root, ignore=shutil.ignore_patterns(".git", "__pycache__"))
            contract_path = root / "plugin-surfaces.json"
            contract = json.loads(contract_path.read_text(encoding="utf-8"))
            contract["screenote_cli"]["approved_commands"].append(["project", "get"])
            contract_path.write_text(json.dumps(contract), encoding="utf-8")
            drift = generated_drift(root)
            self.assertTrue(any(relative in error for error in drift), drift)

    def test_removed_generated_adapter_is_rejected_and_pruned(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            shutil.copytree(REPO_ROOT, root, ignore=shutil.ignore_patterns(".git", "__pycache__"))
            contract_path = root / "plugin-surfaces.json"
            contract = json.loads(contract_path.read_text(encoding="utf-8"))
            skill = next(
                skill
                for plugin in contract["plugins"]
                if plugin["name"] == "screenote"
                for skill in plugin["canonical"]["skills"]
                if skill["name"] == "screenote"
            )
            skill.setdefault("aliases", {})["pi"] = "screenote-renamed"
            contract_path.write_text(json.dumps(contract), encoding="utf-8")

            stale = "plugins/screenote/pi/skills/screenote/SKILL.md"
            replacement = "plugins/screenote/pi/skills/screenote-renamed/SKILL.md"
            non_owned = root / "plugins/screenote/evals/mentions-generator.py"
            non_owned.write_text(
                'MARKER = "GENERATED BY scripts/generate-agent-packages.py"\n',
                encoding="utf-8",
            )
            drift = generated_drift(root)
            self.assertTrue(any(f"unexpected generated file: {stale}" == error for error in drift), drift)
            self.assertTrue(any(replacement in error for error in drift), drift)

            changed = write_generated_files(root)
            self.assertIn(stale, changed)
            self.assertFalse((root / stale).exists())
            self.assertFalse((root / stale).parent.exists())
            self.assertTrue((root / replacement).is_file())
            self.assertTrue(non_owned.is_file())
            self.assertEqual([], generated_drift(root))

    def test_every_plugin_has_pi_and_openclaw_metadata_and_adapters(self):
        contract = load_contract(REPO_ROOT)
        for plugin in contract["plugins"]:
            root = REPO_ROOT / plugin["path"]
            with self.subTest(plugin=plugin["name"]):
                package = json.loads((root / "package.json").read_text())
                manifest = json.loads((root / "openclaw.plugin.json").read_text())
                self.assertEqual(["./pi/skills"], package["pi"]["skills"])
                self.assertEqual(["./openclaw/index.js"], package["openclaw"]["extensions"])
                tested_openclaw = plugin["platforms"]["openclaw"]["tested_host_version"]
                self.assertEqual(
                    {"pluginApi": f">={tested_openclaw}"},
                    package["openclaw"]["compat"],
                )
                self.assertTrue((root / "openclaw/index.js").is_file())
                self.assertEqual(["./openclaw/skills"], manifest["skills"])
                self.assertEqual(plugin["name"], manifest["id"])
                self.assertFalse(manifest["configSchema"]["additionalProperties"])
                for skill in plugin["canonical"]["skills"]:
                    for platform in ("pi", "openclaw"):
                        alias = skill.get("aliases", {}).get(platform, skill["name"])
                        adapter = root / platform / "skills" / alias / "SKILL.md"
                        body = adapter.read_text()
                        self.assertIn("GENERATED BY scripts/generate-agent-packages.py", body)
                        self.assertIn(skill["path"], body)

    def test_llm_wiki_adapters_inline_reviewed_behavior_without_runtime_delegation(self):
        contract = load_contract(REPO_ROOT)
        plugin = next(plugin for plugin in contract["plugins"] if plugin["name"] == "llm-wiki")
        self.assertEqual("inline", plugin["canonical"]["adapter_mode"])
        root = REPO_ROOT / plugin["path"]

        for skill in plugin["canonical"]["skills"]:
            canonical = (root / skill["path"]).read_text(encoding="utf-8")
            canonical_heading = next(
                line for line in canonical.splitlines() if line.startswith("# ")
            )
            for platform in ("pi", "openclaw"):
                alias = skill.get("aliases", {}).get(platform, skill["name"])
                adapter = (root / platform / "skills" / alias / "SKILL.md").read_text(
                    encoding="utf-8"
                )
                with self.subTest(skill=skill["name"], platform=platform):
                    self.assertIn(canonical_heading, adapter)
                    self.assertNotIn("Load and follow the canonical skill", adapter)
                    self.assertNotIn("invocation working directory", adapter)
                    marker = (
                        "<!-- GENERATED BY scripts/generate-agent-packages.py; "
                        "DO NOT EDIT -->"
                    )
                    rendered_semantics = adapter.split(marker, 1)[1].lstrip("\n").encode()
                    self.assertEqual(
                        canonical_semantic_bytes(canonical), rendered_semantics
                    )

    def test_llm_wiki_canonical_skills_do_not_shadow_claude_builtins(self):
        contract = load_contract(REPO_ROOT)
        plugin = next(plugin for plugin in contract["plugins"] if plugin["name"] == "llm-wiki")
        skill_names = {skill["name"] for skill in plugin["canonical"]["skills"]}

        self.assertNotIn("status", skill_names)

    def test_llm_wiki_cross_skill_names_and_package_paths_resolve_on_every_host(self):
        contract = load_contract(REPO_ROOT)
        plugin = next(plugin for plugin in contract["plugins"] if plugin["name"] == "llm-wiki")
        root = REPO_ROOT / plugin["path"]
        skills = {skill["name"]: skill for skill in plugin["canonical"]["skills"]}
        references = {
            "wiki-plan": ("research", "bootstrap"),
            "research": ("bootstrap",),
            "wiki-status": ("upgrade",),
        }

        for platform in ("claude", "codex", "pi", "openclaw"):
            for source_name, target_names in references.items():
                source = skills[source_name]
                if platform in ("pi", "openclaw"):
                    source_alias = source.get("aliases", {}).get(platform, source_name)
                    source_path = root / platform / "skills" / source_alias / "SKILL.md"
                else:
                    source_path = root / source["path"]
                body = source_path.read_text(encoding="utf-8")

                for target_name in target_names:
                    target = skills[target_name]
                    target_alias = target.get("aliases", {}).get(platform, target_name)
                    if platform in ("pi", "openclaw"):
                        target_path = root / platform / "skills" / target_alias / "SKILL.md"
                    else:
                        target_path = root / target["path"]
                    with self.subTest(
                        platform=platform, source=source_name, target=target_name
                    ):
                        self.assertTrue(target_path.is_file(), target_path)
                        self.assertIn(target_alias, body)

            status = skills["wiki-status"]
            if platform in ("pi", "openclaw"):
                status_alias = status["aliases"][platform]
                status_path = root / platform / "skills" / status_alias / "SKILL.md"
            else:
                status_path = root / status["path"]
            status_body = status_path.read_text(encoding="utf-8")
            self.assertIn("skills/upgrade/scripts/upgrade-project.sh", status_body)
            self.assertNotIn("../upgrade/SKILL.md", status_body)

        self.assertTrue(
            (root / "skills" / "upgrade" / "scripts" / "upgrade-project.sh").is_file()
        )

    def test_packages_survive_isolated_copy(self):
        self.assertEqual([], validate_isolated_packages(REPO_ROOT))

    def test_symlinks_and_path_escapes_are_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "demo"
            (root / "skills" / "demo").mkdir(parents=True)
            (root / "skills" / "demo" / "SKILL.md").write_text("---\nname: demo\ndescription: demo\n---\n")
            (root / "pi" / "skills" / "demo").mkdir(parents=True)
            adapter = root / "pi" / "skills" / "demo" / "SKILL.md"
            adapter.write_text("[canonical](../../../../outside.md)\n")
            errors = validate_package_tree(root)
            self.assertTrue(any("escapes package" in error for error in errors), errors)
            (root / "bad-link").symlink_to(root / "skills")
            errors = validate_package_tree(root)
            self.assertTrue(any("symlink" in error for error in errors), errors)

    def test_copy_does_not_depend_on_checkout_neighbors(self):
        contract = load_contract(REPO_ROOT)
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "package"
            source = REPO_ROOT / contract["plugins"][0]["path"]
            shutil.copytree(source, destination)
            self.assertEqual([], validate_package_tree(destination))


if __name__ == "__main__":
    unittest.main()
