import json
import shutil
import tempfile
import unittest
from pathlib import Path

from scripts.plugin_surfaces import (
    generate_files,
    load_contract,
    validate_isolated_packages,
    validate_package_tree,
)


REPO_ROOT = Path(__file__).resolve().parents[1]


class GeneratedPackageTests(unittest.TestCase):
    def test_checked_in_generation_matches_deterministic_render(self):
        first = generate_files(REPO_ROOT)
        second = generate_files(REPO_ROOT)
        self.assertEqual(first, second)
        mismatches = [path for path, content in first.items() if (REPO_ROOT / path).read_bytes() != content]
        self.assertEqual([], mismatches)

    def test_every_plugin_has_pi_and_openclaw_metadata_and_adapters(self):
        contract = load_contract(REPO_ROOT)
        for plugin in contract["plugins"]:
            root = REPO_ROOT / plugin["path"]
            with self.subTest(plugin=plugin["name"]):
                package = json.loads((root / "package.json").read_text())
                manifest = json.loads((root / "openclaw.plugin.json").read_text())
                self.assertEqual(["./pi/skills"], package["pi"]["skills"])
                self.assertEqual(["./openclaw/skills"], manifest["skills"])
                self.assertEqual(plugin["name"], manifest["id"])
                self.assertFalse(manifest["configSchema"]["additionalProperties"])
                for skill in plugin["canonical"]["skills"]:
                    for platform in ("pi", "openclaw"):
                        alias = skill.get("aliases", {}).get(platform, skill["name"])
                        adapter = root / platform / "skills" / alias / "SKILL.md"
                        body = adapter.read_text()
                        self.assertIn("GENERATED BY scripts/generate-agent-packages.py", body)
                        self.assertIn(skill["path"], body)

    def test_packages_survive_isolated_copy(self):
        self.assertEqual([], validate_isolated_packages(REPO_ROOT))

    def test_symlinks_and_path_escapes_are_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "demo"
            (root / "skills" / "demo").mkdir(parents=True)
            (root / "skills" / "demo" / "SKILL.md").write_text("---\nname: demo\ndescription: demo\n---\n")
            (root / "pi" / "skills" / "demo").mkdir(parents=True)
            adapter = root / "pi" / "skills" / "demo" / "SKILL.md"
            adapter.write_text("[canonical](../../../../outside.md)\n")
            errors = validate_package_tree(root)
            self.assertTrue(any("escapes package" in error for error in errors), errors)
            (root / "bad-link").symlink_to(root / "skills")
            errors = validate_package_tree(root)
            self.assertTrue(any("symlink" in error for error in errors), errors)

    def test_copy_does_not_depend_on_checkout_neighbors(self):
        contract = load_contract(REPO_ROOT)
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "package"
            source = REPO_ROOT / contract["plugins"][0]["path"]
            shutil.copytree(source, destination)
            self.assertEqual([], validate_package_tree(destination))


if __name__ == "__main__":
    unittest.main()
