#!/usr/bin/env bash

# GENERATED BY scripts/generate-agent-packages.py; DO NOT EDIT

declare -ar SCREENOTE_APPROVED_COMMANDS=(
  project
  list
  project
  create
  page
  list
  screenshot
  list
  screenshot
  create
  annotation
  list
  annotation
  get
  comment
  add
  snapshot
  --manifest
)

screenote_command_is_approved() {
  (($# == 2)) || return 1
  local index
  for ((index = 0; index < ${#SCREENOTE_APPROVED_COMMANDS[@]}; index += 2)); do
    if [[ $1 == "${SCREENOTE_APPROVED_COMMANDS[index]}" &&
          $2 == "${SCREENOTE_APPROVED_COMMANDS[index + 1]}" ]]; then
      return 0
    fi
  done
  return 1
}
