// GENERATED BY scripts/generate-agent-packages.py; DO NOT EDIT.
// This content-only entry activates the manifest-declared skill roots without
// registering tools, services, hooks, providers, or configuration side effects.

export default {
  id: "agent-reviewer",
  name: "Agent Reviewer",
  description: "Clone your team's best code reviewers from their PR history and run them as a review panel.",
  register() {},
};
