#!/usr/bin/env python3
"""Shared parsing and validation for the repository plugin surface contract."""

from __future__ import annotations

import json
import hashlib
import re
import shutil
import tempfile
from pathlib import Path, PurePosixPath
from typing import Any, Iterable
from urllib.parse import unquote


PLATFORMS = ("claude", "codex", "pi", "openclaw")
DISTRIBUTION_STATES = {"stable", "experimental", "deprecated", "excluded"}
GENERATOR = "scripts/generate-agent-packages.py"
MARKDOWN_LINK = re.compile(r"\[[^\]]*\]\(([^)]+)\)")
HEADING = re.compile(r"^(#{1,6})\s+(.+?)\s*$")


def load_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def load_contract(root: Path) -> dict[str, Any]:
    payload = load_json(root / "plugin-surfaces.json")
    if not isinstance(payload, dict):
        raise ValueError("plugin-surfaces.json must contain an object")
    return payload


def canonical_semantic_bytes(markdown: str) -> bytes:
    """Normalize a canonical skill while excluding host-only frontmatter."""

    lines = markdown.replace("\r\n", "\n").replace("\r", "\n").splitlines()
    if lines and lines[0].strip() == "---":
        try:
            end = next(index for index, line in enumerate(lines[1:], 1) if line.strip() == "---")
        except StopIteration:
            end = -1
        if end >= 0:
            lines = lines[end + 1 :]
    normalized = [re.sub(r"[ \t]+$", "", line) for line in lines]
    while normalized and not normalized[0]:
        normalized.pop(0)
    while normalized and not normalized[-1]:
        normalized.pop()
    return ("\n".join(normalized) + "\n").encode()


def _section_hashes(markdown: str) -> dict[str, str]:
    sections: dict[str, list[str]] = {"preamble": []}
    current = "preamble"
    counts: dict[str, int] = {}
    for line in canonical_semantic_bytes(markdown).decode().splitlines():
        match = HEADING.match(line)
        if match:
            base = f"{len(match.group(1))}:{match.group(2).strip().lower()}"
            counts[base] = counts.get(base, 0) + 1
            current = base if counts[base] == 1 else f"{base}#{counts[base]}"
            sections[current] = [line]
        else:
            sections[current].append(line)
    return {
        name: hashlib.sha256(("\n".join(lines).strip() + "\n").encode()).hexdigest()
        for name, lines in sections.items()
        if any(line.strip() for line in lines)
    }


def _frontmatter_value(markdown: str, key: str) -> str | None:
    lines = markdown.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if line.startswith(f"{key}:"):
            value = line.split(":", 1)[1].strip()
            if value.startswith('"') and value.endswith('"'):
                try:
                    return json.loads(value)
                except json.JSONDecodeError:
                    pass
            return value
    return None


def _json_bytes(payload: Any) -> bytes:
    return (json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n").encode()


def _adapter_bytes(
    plugin: dict[str, Any], skill: dict[str, Any], platform: str, plugin_root: Path
) -> bytes:
    alias = skill.get("aliases", {}).get(platform, skill["name"])
    canonical = skill["path"]
    # Both generated roots have the same depth: <platform>/skills/<name>/SKILL.md.
    relative = Path("../../..") / canonical
    source = plugin_root / canonical
    description = _frontmatter_value(source.read_text(encoding="utf-8"), "description") or plugin["metadata"]["description"]
    body = f"""---
name: {alias}
description: {json.dumps(description, ensure_ascii=False)}
metadata:
  generated-from: {canonical}
  generated-for: {platform}
---

<!-- GENERATED BY {GENERATOR}; DO NOT EDIT -->

# {alias}

Load and follow the canonical skill at [{canonical}]({relative.as_posix()}).
That in-package file is the behavioral authority. Resolve its agents, scripts,
references, context, and output paths relative to this plugin package or the
invocation working directory exactly as the canonical skill specifies.
"""
    return body.encode()


def _legacy_adapter_bytes(plugin: dict[str, Any], entry: dict[str, Any]) -> bytes:
    canonical = plugin["canonical"]["skills"][0]["path"]
    relative = (Path("..") / canonical).as_posix()
    usage = "\n".join(entry["usage"])
    body = f"""---
description: {json.dumps(f"Compatibility entrypoint for the {entry['mode']} mode in {plugin['name']}.", ensure_ascii=False)}
argument-hint: {json.dumps(entry.get("arguments", ""), ensure_ascii=False)}
---

<!-- GENERATED BY {GENERATOR}; DO NOT EDIT -->

# /{entry['name']}

This legacy Claude Code command selects mode `{entry['mode']}` from the
canonical [{canonical}]({relative}) workflow.

Pass `$ARGUMENTS` unchanged to that mode. The canonical skill owns validation,
defaults, resources, safety rules, stop conditions, and artifact paths.

Established usage:

```text
{usage}
```
"""
    return body.encode()


def _resource_digest(root: Path, relative: str) -> dict[str, Any]:
    path = root / relative
    if not path.exists():
        return {"exists": False, "sha256": None}
    if path.is_file():
        return {"exists": True, "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}
    digest = hashlib.sha256()
    files: list[str] = []
    for child in sorted(item for item in path.rglob("*") if item.is_file() and not item.is_symlink()):
        child_relative = child.relative_to(root).as_posix()
        files.append(child_relative)
        digest.update(child_relative.encode() + b"\0" + child.read_bytes() + b"\0")
    return {"exists": True, "sha256": digest.hexdigest(), "files": files}


def generate_files(root: Path) -> dict[str, bytes]:
    """Render all generated package files and the semantic lock in memory."""

    root = root.resolve()
    contract = load_contract(root)
    rendered: dict[str, bytes] = {}
    lock: dict[str, Any] = {
        "lock_version": 1,
        "contract_version": contract["contract_version"],
        "generated_by": GENERATOR,
        "plugins": {},
    }
    for plugin in contract["plugins"]:
        plugin_root = root / plugin["path"]
        metadata = plugin["metadata"]
        package = {
            "name": plugin["name"],
            "version": plugin["version"],
            "description": metadata["description"],
            "homepage": metadata["homepage"],
            "repository": metadata["repository"],
            "license": metadata["license"],
            "keywords": metadata["npm_keywords"],
            "pi": {"skills": ["./pi/skills"]},
            "x-agent-plugins-generated": GENERATOR,
        }
        openclaw = {
            "id": plugin["name"],
            "name": metadata["display_name"],
            "description": metadata["description"],
            "version": plugin["version"],
            "skills": ["./openclaw/skills"],
            "configSchema": {"type": "object", "additionalProperties": False, "properties": {}},
        }
        rendered[f"{plugin['path']}/package.json"] = _json_bytes(package)
        rendered[f"{plugin['path']}/openclaw.plugin.json"] = _json_bytes(openclaw)

        plugin_lock: dict[str, Any] = {
            "version": plugin["version"],
            "canonical": {},
            "resources": {},
            "adapters": {},
            "legacy_entrypoints": {},
        }
        for skill in plugin["canonical"]["skills"]:
            canonical_path = plugin_root / skill["path"]
            canonical_bytes = canonical_path.read_bytes()
            markdown = canonical_bytes.decode("utf-8")
            plugin_lock["canonical"][skill["path"]] = {
                "sha256": hashlib.sha256(canonical_bytes).hexdigest(),
                "semantic_sha256": hashlib.sha256(canonical_semantic_bytes(markdown)).hexdigest(),
                "sections": _section_hashes(markdown),
            }
            for platform in ("pi", "openclaw"):
                alias = skill.get("aliases", {}).get(platform, skill["name"])
                relative = f"{plugin['path']}/{platform}/skills/{alias}/SKILL.md"
                adapter = _adapter_bytes(plugin, skill, platform, plugin_root)
                rendered[relative] = adapter
                plugin_lock["adapters"][f"{platform}/skills/{alias}/SKILL.md"] = {
                    "sha256": hashlib.sha256(adapter).hexdigest(),
                    "canonical": skill["path"],
                    "canonical_semantic_sha256": plugin_lock["canonical"][skill["path"]]["semantic_sha256"],
                    "overlays": ["frontmatter", "invocation", "install-path"],
                }
        for entry in plugin["legacy_entrypoints"]:
            if not entry["path"].startswith("commands/"):
                continue
            relative = f"{plugin['path']}/{entry['path']}"
            adapter = _legacy_adapter_bytes(plugin, entry)
            rendered[relative] = adapter
            plugin_lock["legacy_entrypoints"][entry["path"]] = {
                "sha256": hashlib.sha256(adapter).hexdigest(),
                "canonical": plugin["canonical"]["skills"][0]["path"],
                "mode": entry["mode"],
                "arguments": entry.get("arguments", ""),
                "overlays": ["frontmatter", "invocation"],
            }
        for resource in plugin["resources"]:
            relative = resource if isinstance(resource, str) else resource["path"]
            plugin_lock["resources"][relative] = _resource_digest(plugin_root, relative)
        lock["plugins"][plugin["name"]] = plugin_lock

    rendered["plugin-surfaces.lock.json"] = _json_bytes(lock)
    return rendered


def write_generated_files(root: Path) -> list[str]:
    changed: list[str] = []
    for relative, content in generate_files(root).items():
        path = root / relative
        if path.is_file() and path.read_bytes() == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        changed.append(relative)
    return changed


def generated_drift(root: Path) -> list[str]:
    drift: list[str] = []
    for relative, content in generate_files(root).items():
        path = root / relative
        if not path.is_file():
            drift.append(f"missing generated file: {relative}")
        elif path.read_bytes() != content:
            drift.append(f"generated file differs: {relative}")
    return drift


def _is_within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def validate_package_tree(package_root: Path) -> list[str]:
    """Validate a copied package without consulting its repository neighbors."""

    package_root = package_root.resolve()
    errors: list[str] = []
    for path in sorted(package_root.rglob("*")):
        if path.is_symlink():
            errors.append(f"{path.relative_to(package_root)}: symlink is not allowed")
            continue
        if not path.is_file() or path.suffix.lower() != ".md":
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for raw_target in MARKDOWN_LINK.findall(text):
            target = raw_target.strip().split(maxsplit=1)[0].strip("<>")
            if not target or target.startswith(("#", "http:", "https:", "mailto:", "data:")):
                continue
            target = unquote(target.split("#", 1)[0])
            if not target or any(marker in target for marker in ("<", ">", "$", "*")):
                continue
            resolved = (path.parent / target).resolve()
            if not _is_within(resolved, package_root):
                errors.append(f"{path.relative_to(package_root)}: reference escapes package: {raw_target}")
            elif not resolved.exists():
                errors.append(f"{path.relative_to(package_root)}: missing referenced path: {raw_target}")
    for relative in ("package.json", "openclaw.plugin.json"):
        path = package_root / relative
        if path.exists():
            try:
                load_json(path)
            except (OSError, json.JSONDecodeError) as exc:
                errors.append(f"{relative}: invalid JSON: {exc}")
    return errors


def validate_isolated_packages(root: Path) -> list[str]:
    errors: list[str] = []
    contract = load_contract(root)
    with tempfile.TemporaryDirectory(prefix="agent-plugin-packages-") as directory:
        temporary_root = Path(directory)
        for plugin in contract["plugins"]:
            source = root / plugin["path"]
            destination = temporary_root / plugin["name"]
            shutil.copytree(source, destination, symlinks=True)
            for error in validate_package_tree(destination):
                errors.append(f"{plugin['name']}: {error}")
            for surface in ("pi", "openclaw"):
                declared_root = destination / surface / "skills"
                if not declared_root.is_dir():
                    errors.append(f"{plugin['name']}: missing {surface}/skills")
            for skill in plugin["canonical"]["skills"]:
                canonical = destination / skill["path"]
                if not canonical.is_file():
                    errors.append(f"{plugin['name']}: missing canonical skill {skill['path']}")
    return errors


def _catalog_entries(root: Path, relative_path: str, codex: bool) -> tuple[dict[str, str], list[str]]:
    errors: list[str] = []
    path = root / relative_path
    try:
        payload = load_json(path)
    except (OSError, json.JSONDecodeError) as exc:
        return {}, [f"{relative_path}: cannot read catalog: {exc}"]

    entries: dict[str, str] = {}
    for index, entry in enumerate(payload.get("plugins", [])):
        label = f"{relative_path}.plugins[{index}]"
        if not isinstance(entry, dict) or not isinstance(entry.get("name"), str):
            errors.append(f"{label}: missing plugin name")
            continue
        name = entry["name"]
        raw_source = entry.get("source")
        source = raw_source.get("path") if codex and isinstance(raw_source, dict) else raw_source
        if not isinstance(source, str):
            errors.append(f"{label}: missing source path")
            continue
        if name in entries:
            errors.append(f"{label}: duplicate plugin name {name!r}")
        entries[name] = source
    return entries, errors


def _approval_errors(value: Any, label: str) -> list[str]:
    if not isinstance(value, dict):
        return [f"{label}: requires approval with reason, owner, and review_condition"]
    missing = [key for key in ("reason", "owner", "review_condition") if not value.get(key)]
    if missing:
        return [f"{label}: requires approval; missing {', '.join(missing)}"]
    return []


def _relative_path_error(value: Any, label: str) -> str | None:
    if not isinstance(value, str) or not value:
        return f"{label}: path must be a non-empty string"
    path = PurePosixPath(value)
    if path.is_absolute() or ".." in path.parts:
        return f"{label}: path escapes the plugin package: {value!r}"
    return None


def _iter_declared_paths(plugin: dict[str, Any]) -> Iterable[tuple[str, str, bool]]:
    canonical = plugin.get("canonical", {})
    for index, skill in enumerate(canonical.get("skills", [])):
        if isinstance(skill, dict):
            yield f"canonical.skills[{index}].path", skill.get("path"), True
    for index, resource in enumerate(plugin.get("resources", [])):
        if isinstance(resource, str):
            yield f"resources[{index}]", resource, True
        elif isinstance(resource, dict):
            yield f"resources[{index}].path", resource.get("path"), bool(resource.get("required", True))
    for platform_name, platform in plugin.get("platforms", {}).items():
        if not isinstance(platform, dict):
            continue
        manifest = platform.get("manifest")
        if manifest:
            # Pi and OpenClaw files are declared by U1 and materialized by U2.
            required = platform_name in {"claude", "codex"}
            yield f"platforms.{platform_name}.manifest", manifest, required
        for index, root in enumerate(platform.get("skill_roots", [])):
            if isinstance(root, str):
                yield f"platforms.{platform_name}.skill_roots[{index}]", root, False


def validate_repository(root: Path) -> list[str]:
    """Return all contract/inventory errors without mutating the checkout."""

    root = root.resolve()
    errors: list[str] = []
    contract_path = root / "plugin-surfaces.json"
    try:
        contract = load_json(contract_path)
    except (OSError, json.JSONDecodeError) as exc:
        return [f"plugin-surfaces.json: cannot read contract: {exc}"]

    claude, catalog_errors = _catalog_entries(root, ".claude-plugin/marketplace.json", False)
    errors.extend(catalog_errors)
    codex, catalog_errors = _catalog_entries(root, ".agents/plugins/marketplace.json", True)
    errors.extend(catalog_errors)

    plugins_dir = root / "plugins"
    directories = {path.name for path in plugins_dir.iterdir() if path.is_dir()} if plugins_dir.is_dir() else set()
    claude_names = set(claude)
    codex_names = set(codex)
    catalog_union = claude_names | codex_names

    for name in sorted(catalog_union - directories):
        errors.append(f"catalog-only plugin {name!r}: no plugins/{name} directory")
    for name in sorted(directories - catalog_union):
        errors.append(f"directory-only plugin {name!r}: missing marketplace registrations")
    for name in sorted(claude_names ^ codex_names):
        errors.append(f"catalog mismatch for {name!r}: plugin must appear in both root catalogs")

    raw_plugins = contract.get("plugins")
    if not isinstance(raw_plugins, list):
        return errors + ["plugin-surfaces.json.plugins: must be an array"]
    contract_plugins: dict[str, dict[str, Any]] = {}
    for index, plugin in enumerate(raw_plugins):
        label = f"plugins[{index}]"
        if not isinstance(plugin, dict) or not isinstance(plugin.get("name"), str):
            errors.append(f"{label}: missing plugin name")
            continue
        name = plugin["name"]
        if name in contract_plugins:
            errors.append(f"{label}: duplicate plugin name {name!r}")
        contract_plugins[name] = plugin

    contract_names = set(contract_plugins)
    for name in sorted((catalog_union | directories) - contract_names):
        errors.append(f"inventory plugin {name!r}: missing contract entry")
    for name in sorted(contract_names - (catalog_union | directories)):
        errors.append(f"contract-only plugin {name!r}: no catalog or directory entry")

    expected_platforms = set(PLATFORMS)
    declared_global = contract.get("compatibility", {}).get("platforms")
    if declared_global != list(PLATFORMS):
        errors.append(f"compatibility.platforms: expected {list(PLATFORMS)!r}")

    for name, plugin in sorted(contract_plugins.items()):
        label = f"plugins.{name}"
        expected_path = f"plugins/{name}"
        if plugin.get("path") != expected_path:
            errors.append(f"{label}.path: path mismatch; expected {expected_path!r}")

        stability = plugin.get("stability")
        if stability not in DISTRIBUTION_STATES:
            errors.append(f"{label}: missing stability or invalid distribution state")
        if stability in {"deprecated", "excluded"}:
            errors.extend(_approval_errors(plugin.get("approval"), f"{label}.{stability}"))

        platforms = plugin.get("platforms")
        if not isinstance(platforms, dict):
            errors.append(f"{label}.platforms: missing platform declarations")
            platforms = {}
        missing_platforms = expected_platforms - set(platforms)
        extra_platforms = set(platforms) - expected_platforms
        for platform_name in sorted(missing_platforms):
            errors.append(f"{label}.platforms: missing platform {platform_name!r}")
        for platform_name in sorted(extra_platforms):
            errors.append(f"{label}.platforms: unknown platform {platform_name!r}")
        for platform_name, surface in platforms.items():
            surface_label = f"{label}.platforms.{platform_name}"
            if not isinstance(surface, dict):
                errors.append(f"{surface_label}: must be an object")
                continue
            support = surface.get("support")
            if support not in {"supported", "unsupported"}:
                errors.append(f"{surface_label}.support: must be supported or unsupported")
            if support == "unsupported":
                errors.extend(_approval_errors(surface.get("approval"), surface_label))
            minimum = surface.get("minimum_host_version")
            evidence = surface.get("minimum_evidence")
            if minimum is None and evidence != "upstream_minimum_unspecified":
                errors.append(
                    f"{surface_label}: null minimum_host_version requires upstream_minimum_unspecified"
                )

        version = plugin.get("version")
        plugin_root = root / expected_path
        if name in claude:
            source = claude[name]
            if source != f"./{expected_path}":
                errors.append(f"{label}: path mismatch in Claude catalog: {source!r}")
            claude_entry = next(
                (entry for entry in load_json(root / ".claude-plugin/marketplace.json").get("plugins", []) if entry.get("name") == name),
                {},
            )
            if claude_entry.get("version") != version:
                errors.append(f"{label}: version mismatch with Claude catalog")
        if name in codex and codex[name] != f"./{expected_path}":
            errors.append(f"{label}: path mismatch in Codex catalog: {codex[name]!r}")

        for manifest in (".claude-plugin/plugin.json", ".codex-plugin/plugin.json", "package.json"):
            path = plugin_root / manifest
            if not path.is_file():
                continue
            try:
                marker = load_json(path).get("version")
            except (OSError, json.JSONDecodeError) as exc:
                errors.append(f"{label}.{manifest}: invalid JSON: {exc}")
                continue
            if marker is not None and marker != version:
                errors.append(f"{label}: version mismatch with {manifest}")

        for field, value, required in _iter_declared_paths(plugin):
            path_error = _relative_path_error(value, f"{label}.{field}")
            if path_error:
                errors.append(path_error)
                continue
            if required and not (plugin_root / value).exists():
                errors.append(f"{label}.{field}: declared path does not exist: {value!r}")

    return errors


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    errors = validate_repository(args.root)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    print("Validated plugin inventory and surface contract.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
