// GENERATED BY scripts/generate-agent-packages.py; DO NOT EDIT.
// This content-only entry activates the manifest-declared skill roots without
// registering tools, services, hooks, providers, or configuration side effects.

export default {
  id: "screenote",
  name: "Screenote",
  description: "Capture pages, publish screenshots, and retrieve visual feedback through the Screenote OAuth CLI.",
  register() {},
};
